/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/FI7vOOYTtaS
 */
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';

export function HeroSection() {
  return (
    <section
      key='1'
      className='w-full py-12 md:py-24 lg:py-32 xl:py-48 bg-gray-100 dark:bg-gray-800'
    >
      <div className='container px-4 md:px-6'>
        <div className='flex flex-col items-center space-y-4 text-center'>
          <div className='space-y-2'>
            <h1 className='text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl lg:text-6xl/none text-gray-800 dark:text-white'>
              Subscribely
            </h1>
            <p className='mx-auto max-w-[700px] text-gray-600 md:text-xl dark:text-gray-400'>
              The complete platform to manage newsletters
            </p>
          </div>
          <div className='w-full max-w-sm space-y-2'>
            <form className='flex space-x-2'>
              <Input
                className='max-w-lg flex-1'
                placeholder='Enter your email'
                type='email'
              />
              <Button type='submit'>Get Started</Button>
            </form>
          </div>
          <div className='max-w-3xl mx-auto mt-8 space-y-4'>
            <p className='text-lg text-gray-700 dark:text-gray-400'>
              Subscribely offers a seamless experience for managing your
              newsletters. From creating engaging content to analyzing
              subscriber engagement, we&apos;ve got you covered.
            </p>
            <div className='grid grid-cols-2 gap-4'>
              <div className='p-4 bg-white dark:bg-gray-900 rounded-lg shadow-lg'>
                <h3 className='text-xl font-semibold'>Features</h3>
                <ul className='list-disc list-inside space-y-2 text-gray-800 dark:text-gray-300'>
                  <li>Customizable templates</li>
                  <li>Subscriber segmentation</li>
                  <li>Performance analytics</li>
                </ul>
              </div>
              <div className='p-4 bg-white dark:bg-gray-900 rounded-lg shadow-lg'>
                <h3 className='text-xl font-semibold'>Benefits</h3>
                <ul className='list-disc list-inside space-y-2 text-gray-800 dark:text-gray-300'>
                  <li>Increase reader engagement</li>
                  <li>Track campaign success</li>
                  <li>Save time with automation</li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
